### ISSUE TITLE
Seem to be getting an error when it DM's you

### ISSUE THREAD

**Issue by AKASGaming** [jowsey/discord.js-menu#1]
**(node:5264) UnhandledPromiseRejectionWarning: DiscordAPIError: Unknown Message
    at RequestHandler.execute (C:\Users\Kyle\Desktop\Bot\node_modules\discord.js\src\rest\RequestHandler.js:170:25)
    at processTicksAndRejections (internal/process/task_queues.js:88:5)
(node:5264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)**

https://pastebin.com/zfKkN3Te

**Comment by jowsey** [comment]
Answered on Discord.
Didn't seem to be related to my library, "Unknown Message" probably means somewhere along the line your bot messed up and didn't send the menu as intended. Will try to update the library soon with better error messages for making things like this easier.

**Comment by MirayXS** [comment]
```
DiscordAPIError: Cannot execute action on a DM channel
```
I would suggest you to ignore the error by doing this in your code.

```js
if (message.channel.type === 'dm') return message.channel.send("DiscordAPIError: Cannot execute action on a DM channel")
```
