### ISSUE TITLE
Extra Embed Options

### ISSUE THREAD

**Issue by HaythamQuake** [jowsey/discord.js-menu#14]
Hello there! Firstly I just want to say I love this menu creator, it makes it so easy to get exactly what I've been trying to achieve for a bot (I'm new at coding)!
I was wondering if you plan to add the options to add colors and images (.setColor and .setImage) for the embed as I noticed those are things that can be done with typical coded embeds. As great as it is, I want to be able to make it also a little bit more visually appealing.
Thank you and take care!

**Comment by mihirgarg01** [comment]
.setColor is actually just color: `<Your Color>`,
.setImage is just image: { url : `<URL` }

Check This Link Out, It Should Help You.
https://discordjs.guide/popular-topics/embeds.html#using-an-embed-object

**Comment by HaythamQuake** [comment]
> .setColor is actually just color: `<Your Color>`,
> .setImage is just image: { url : `<URL` }
> 
> Check This Link Out, It Should Help You.
> https://discordjs.guide/popular-topics/embeds.html#using-an-embed-object

Yes, that worked! Thank you so much!
