### ISSUE TITLE
Usage Feedback

### ISSUE THREAD

**Issue by MirayXS** [jowsey/discord.js-menu#2]
# Usage Feedback

## Some things i noticed while coding

```
1. DiscordAPIError: Cannot execute action on a DM channel
```

Fixed by doing the following

```js
if (message.channel.type === 'dm') return message.channel.send("DiscordAPIError: Cannot execute action on a DM channel")
```

Looks like that if i stop the menus through the stop button i get this error. 
..i don't remember correctly because i was testing yesterday.

```
2. DiscordAPIError: Missing Permissions
```

Seems like embeds don't work properly if the bot doesn't have the `MANAGE_MESSAGES` permission on.
..Seems like these permissions are required:

```
READ_MESSAGES
SEND_MESSAGES
EMBED_LINKS
ADD_REACTIONS
```

**Comment by jowsey** [comment]
I've addressed this in v2.0.0 (https://github.com/jowsey/discord.js-menu/commit/e53e40c1746ab125e4e01c0242b0d75d6481bfa6). Apologies for the wait, have had a lot of things to deal with, but finally got a moment to figure this out.
