### ISSUE TITLE
Hello I have problems adding a custom Discord Emoji into the reaction. 

### ISSUE THREAD

**Issue by jonesbang** [jowsey/discord.js-menu#4]
```DiscordAPIError: Unknown Emoji (whilst trying to add reactions to message) | The emoji you were trying to add to page "main" (763244587467800600) probably doesn't exist. You probably entered the ID wrong when adding a custom emoji.```

763244587467800587 is :white_check_mark: and it is not working. Could you check if I went anywhere wrong?

```                reactions: {
                    763244587467800587: 'extra',
                    '▶': 'extra'
                }
            },
```

**Comment by jowsey** [comment]
I believe the Discord API expects IDs to be strings, try putting quotes around the ID and trying again

**Comment by jonesbang** [comment]
I have tried the '' an it still gives me the error 

```[discord.js-menu] DiscordAPIError: Unknown Emoji (whilst trying to add reactions to message) | The emoji you were trying to add to page "main" (763242804121698305) probably doesn't exist. You probably entered the ID wrong when adding a custom emoji.```

**Comment by jowsey** [comment]
How are you getting the ID? If you're right clicking the emoji in a message you might be accidentally getting the ID of the message? If so, try putting a backslash (\) in front of the emoji when you send it and get the ID that way.

Please let me know if you still get an error after doing that.

**Comment by jowsey** [comment]
> How are you getting the ID? If you're right clicking the emoji in a message you might be accidentally getting the ID of the message? If so, try putting a backslash () in front of the emoji when you send it and get the ID that way.
> 
> Please let me know if you still get an error after doing that.

I also notice your ID changed in the second attempt, leading me to believe you are copying the message ID

**Comment by jonesbang** [comment]
Yep, it is working now. Thanks for the help
