### ISSUE TITLE
Embed Parts

### ISSUE THREAD

**Issue by Jeydin21** [jowsey/discord.js-menu#5]
How do I set an author for the embed? How do I set the footer for the embed? Can you go over these things?

**Comment by jowsey** [comment]
https://discordjs.guide/popular-topics/embeds.html#using-the-richembedmessageembed-constructor

This goes over everything you need to do  to create custom embeds, including the author and footer.

**Comment by Jeydin21** [comment]
Oh

**Comment by Jeydin21** [comment]
Another thing: Instead of having the bot delete all the reactions and then adding them again when switching to another page, can't it just edit the message, just like that? Why does it have to delete the reactions as well?

**Comment by jowsey** [comment]
What do you mean? If it didn't delete the previous reactions how would it handle pages with different reactions? I'm working on an update which will check if two pages have the same reactions and if so, it won't delete them, but for now it is what it is, sorry.

**Comment by Jeydin21** [comment]
Oh ok then
